#!/usr/bin/env bash
# Install nginx web server
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user the permission to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart the Nginx Service
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
