#!/usr/bin/env bash
# Sends five ping requests to the specified IP address provided as an argument.
# Checks if the host is reachable on the network using the ping command.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
