#!/usr/bin/env bash
#This script displays "Best School" 10 times with a special condition on the 9th iteration

#Initializing counter
counter=0

#Using a while loop to display "Best School" 10 times with a special condition on the 9th iteration
while [ $counter -lt 10 ]
do
	if [ $counter -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
        	echo "Best School"
	fi
	((counter++))
done
