#!/usr/bin/env bash
#This script displays the content of the current directory in a list format
#Only the part of the name after the first dash is displayed

#Using a for loop to iterate over files in the current directory
for file in *
do
	#Checking if the file is not hidden
	if [[ $file != .* ]]; then
		#Extracting the part of the name after the first dash
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
