#!/usr/bin/env bash
# Configures a server as follows:
# Setting localhost to 127.0.0.2
# Setting facebook.com to resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
